# Generated by Django 3.1.12 on 2021-06-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(max_length=100, verbose_name='物件名')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('buildingType', models.CharField(max_length=100, verbose_name='建物の種類（戸建て、集合住宅など）')),
                ('price', models.IntegerField()),
                ('buildingAge', models.IntegerField()),
                ('floor', models.CharField(max_length=100, verbose_name='階建')),
                ('transportation', models.CharField(max_length=100, verbose_name='交通')),
                ('address', models.CharField(max_length=100, verbose_name='所在地')),
                ('showerRoomAndBathRoom', models.CharField(max_length=100, verbose_name='バス、トイレ')),
                ('kitchen', models.CharField(max_length=100, verbose_name='キッチン')),
                ('Feature', models.CharField(max_length=100, verbose_name='設備・サービス')),
                ('other', models.CharField(max_length=100, verbose_name='その他')),
                ('renovation', models.CharField(max_length=100, verbose_name='リフォーム')),
                ('size', models.IntegerField()),
                ('typeOfBuildingConstruction', models.CharField(max_length=100, verbose_name='建物構造')),
                ('image', models.ImageField(upload_to='images', verbose_name='イメージ画像')),
                ('entranceImage', models.ImageField(upload_to='images', verbose_name='エントランス写真')),
                ('exteriorImage', models.ImageField(upload_to='images', verbose_name='外観写真')),
                ('floorPlan', models.ImageField(upload_to='images', verbose_name='間取り図')),
                ('buildingDescription', models.TextField(verbose_name='物件詳細')),
            ],
        ),
    ]
