# Generated by Django 3.1.12 on 2021-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Feature',
            field=models.CharField(blank=True, max_length=100, verbose_name='設備・サービス'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='property',
            name='buildingAge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='buildingDescription',
            field=models.TextField(blank=True, verbose_name='物件詳細'),
        ),
        migrations.AlterField(
            model_name='property',
            name='buildingType',
            field=models.CharField(blank=True, max_length=100, verbose_name='建物の種類（戸建て、集合住宅など）'),
        ),
        migrations.AlterField(
            model_name='property',
            name='entranceImage',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='エントランス写真'),
        ),
        migrations.AlterField(
            model_name='property',
            name='exteriorImage',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='外観写真'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, max_length=100, verbose_name='階建'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floorPlan',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='間取り図'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='イメージ画像'),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchen',
            field=models.CharField(blank=True, max_length=100, verbose_name='キッチン'),
        ),
        migrations.AlterField(
            model_name='property',
            name='other',
            field=models.CharField(blank=True, max_length=100, verbose_name='その他'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='renovation',
            field=models.CharField(blank=True, max_length=100, verbose_name='リフォーム'),
        ),
        migrations.AlterField(
            model_name='property',
            name='showerRoomAndBathRoom',
            field=models.CharField(blank=True, max_length=100, verbose_name='バス、トイレ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='transportation',
            field=models.CharField(blank=True, max_length=100, verbose_name='交通'),
        ),
        migrations.AlterField(
            model_name='property',
            name='typeOfBuildingConstruction',
            field=models.CharField(blank=True, max_length=100, verbose_name='建物構造'),
        ),
    ]
