# Generated by Django 3.1.12 on 2021-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210623_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='buildingAge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
